# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_app', '0002_auto_20180424_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebelt',
            name='gmt',
            field=models.SmallIntegerField(unique=True, verbose_name='GMT'),
        ),
    ]
